### ISSUE TITLE
Mask for Low Complexity Regions

### ISSUE THREAD

**Issue by nicolarhyner** [TillMacher/apscale_blast#2]
Hi Till

After troubleshooting quite a lot with some ESVs that were not assigned to any taxonomic level, but had a 100% sequence match to the reference sequence in MIDORI2, I finally figured out that the culprit was the automatic blastn masking of low complexity regions. Our barcode is very short and apparently contains such low complexity regions (16S mtDNA in mammals). Do you think implementing an option to disable automatic masking of low complexity would be an option for apscale_blast? This would make my life much easier, as I wouldn’t have to manually align or blast ESVs afterwards ;-)

Thanks a lot for all your tools and updates! 
Greetings, Nicola

**Comment by TillMacher** [comment]
Hi Nicola,

sure I can implement that! Could you provide me an example .fasta file to test for this issue (some 20 sequence are fine)?

cheers
Till

**Comment by nicolarhyner** [comment]
Hi Till
Grest! thanks a lot for your quick response. I'll send you a fasta by mail.
cheers, Nicola

**Comment by nicolarhyner** [comment]
Hi Till, I didn't find a working mail anymore and I'll upload the fasta as a .txt here :) 
The problem appears e.g. for the ESVs: 

>3ab500ee70acc009455f4800bd2f5dbe412342a91b6cdfb6f3fb4ae83bbaa20a
>52570ee54bcc2c46b9f4240a83d750554d039d25b9ab03ed42a544d743d4043b
>9793c8c3f032b335348259fcb18b852be850b36d9e36ae090e36f32e5b4819e3

Here, I get “No Match” from apscale_blast from Phylum to Species. On NCBI with blastn, these sequences also give no hits, but when I unselect “Low complexity regions,” I have more success. The ESVs are Apodemus sylvaticus, which also makes perfect sense biologically (for example, the 3ab500… ESV is the most abundant ESV in my dataset, and this mouse is always present).

Thanks a lot for your help!! 
Cheers, Nicola


[lox_complexity.txt](https://github.com/user-attachments/files/17643495/lox_complexity.txt)

**Comment by TillMacher** [comment]
I updated apscale-blast. You can now add "-masking No" and masking will be disabled. This adds "-dust no -soft_masking false" to the blastn command. The default remains "-masking Yes". 

I hope that helps!

**Comment by nicolarhyner** [comment]
Just rerun it after updating apscale_blast and it works perfectly now. Thanks a lot for the quick implementation!
